class Error:
	SUCC = {'code':0,'errmsg':'succ'}
	DBNOTEXIST = {'code':601,'errmsg':'target db is not existed'}
	DBCONNECTERR = {'code':602,'errmsg':'db connect failed!'}
	DBERROR = {'code':603,'errmsg':'db unknown error'}
	DBSQLERR = {'code':604,'errmsg':'sql error.'}
	DBEMPTYERR = {'code':605,'errmsg':'empty result'}
	CGIREQUESTERR = {'code':501,'errmsg':'cgi data error'}
	CGITOKENERROR = {'code':502,'errmsg':'cgi token error'}
	SYSTEMCONFIGMISS = {'code':503,'errmsg':'system config miss'}
	APPSESSIONERR = {'code':201,'errmsg':'need login'}
	APPCONFIGERR = {'code':202,'errmsg':'config file error'}
	MODPARAMERR = {'code':203,'errmsg':'mod function param error'}
	MODDATAEXISTED = {'code':204,'errmsg':'data has exited'}
	PLUGINERR = {'code':701,'errmsg':'plugins parse error'}
	COMPILEERR = {'code':702,'errmsg':'script complie error'}
	ALGORITHMFORMATERR = {'code':703,'errmsg':'algorithm format error'}
	ALGORITHMABORT = {'code':704,'errmsg':'algorithm format error'}
	COMPILE_PRE = {'code':1500,'errmsg':'grammar mistake'}
	COMPILE_SO = {'code':1502,'errmsg':'entry point mistake'}
	COMPILE_PENDING = {'code':1503,'errmsg':'find a same task'}
	API_NOTSUPPORTED = {'code':801,'errmsg':'not supported resource'}
	API_RESERROR = {'code':802,'errmsg':'invalid restful format'}
	API_EXECERROR = {'code':803,'errmsg':'api execute error'}
	API_NOTIMPLEMENT = {'code':804,'errmsg':'api not implement this function'}
	TP_API_NOTFINDCFG = {'code':901,'errmsg':'can not find api or corp in cfg'}
	TP_API_INVAILDMETHOD = {'code':902,'errmsg':'invaild method'}
	ACL_NOTFOUNDUSER = {'code':211,'errmsg':'can not find user acl'}
	CMSACCOUNTMISS = {'code':212,'errmsg':'cms account not existed'}
	DATAREMOVEFAILED = {'code':220,'errmsg':'data remove failed'}
	DATANOTEXISTED = {'code':221,'errmsg':'data not existed'}
	ACLERROR = {'code':222,'errmsg':'Permission denied'}
	DATAFORMATERR = {'code':223,'errmsg':'Data format error'}
